# Instructions to run:
# cd to folder containing this file
# conda env create
# source activate globalai

name: globalai
channels:
- defaults
dependencies:
- python=3.6
- pip==9.0.1
- numpy==1.13.3
- jupyter==1.0
- matplotlib==2.1.0
- scikit-learn==0.19.1
- scipy==0.19.1
- pandas==0.20.3
- pillow==4.2.1
- seaborn==0.8
- h5py==2.7.0
- pytest==3.2.1
- pip:
  - tensorflow==1.4.0
  - keras==2.1.3
